trigger:
  tags:
    include: ['*']
  branches:
    include: ['*']

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: common/build.yml
  - template: common/publish-vsix.yml # Only publish vsix from linux build since we use this to release and want to stay consistent
  - template: common/lint.yml
  # - template: common/test.yml
  - bash: |
      echo ">> Publish to vscode marketplace"
      yarn deploy -p $(VSCODE_MARKETPLACE_TOKEN)
    displayName: Publish VSCode Marketplace
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))

- job: macOS
  pool:
    vmImage: macOS-10.14
  steps:
  - template: common/build.yml
  - template: common/lint.yml
  - template: common/test.yml
